apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-eye-of-sauron
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    
spec:
  rules:
  - host: "todo-app-k8s.com"
    http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: client-service-clusterip
              port:
                number: 80
            
        # - path: /api/?(.*)
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: server-service-clusterip
        #       port:
        #         number: 5000